In [1]:
import pandas as pd
import os
from pathlib import Path

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

In [3]:
DATA_PATH = Path("C:\\Users\\varik\\OneDrive\\Desktop\\aws-batch-data-platform\\data\\raw")

print("Dataset path:", DATA_PATH.resolve())
print("\nFiles found:")

for file in DATA_PATH.glob("*.csv"):
    print(file.name)

Dataset path: C:\Users\varik\OneDrive\Desktop\aws-batch-data-platform\data\raw

Files found:
olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_orders_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [4]:
customers = pd.read_csv(DATA_PATH / "olist_customers_dataset.csv")
geolocation = pd.read_csv(DATA_PATH / "olist_geolocation_dataset.csv")
order_items = pd.read_csv(DATA_PATH / "olist_order_items_dataset.csv")
payments = pd.read_csv(DATA_PATH / "olist_order_payments_dataset.csv")
reviews = pd.read_csv(DATA_PATH / "olist_order_reviews_dataset.csv")
orders = pd.read_csv(DATA_PATH / "olist_orders_dataset.csv")
products = pd.read_csv(DATA_PATH / "olist_products_dataset.csv")
sellers = pd.read_csv(DATA_PATH / "olist_sellers_dataset.csv")
category_translation = pd.read_csv(
    DATA_PATH / "product_category_name_translation.csv"
)

In [5]:
datasets = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
    "category_translation": category_translation
}

In [6]:
summary = []

for name, df in datasets.items():
    summary.append({
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "memory_mb": round(df.memory_usage(deep=True).sum() / (1024 * 1024), 2)
    })

dataset_summary = pd.DataFrame(summary)

dataset_summary

                dataset     rows  columns  memory_mb
0             customers    99441        5      26.59
1           geolocation  1000163        5     129.38
2           order_items   112650        7      35.99
3              payments   103886        5      16.23
4               reviews    99224        7      39.12
5                orders    99441        8      52.94
6              products    32951        9       6.30
7               sellers     3095        4       0.59
8  category_translation       71        2       0.01

In [7]:
dataset_summary.to_csv(
    "../docs/dataset_inventory.csv",
    index=False
)

In [8]:
for name, df in datasets.items():
    print("=" * 100)
    print(f"DATASET: {name.upper()}")
    print("=" * 100)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nFirst 3 Rows:")
    display(df.head(3))

====================================================================================================
DATASET: CUSTOMERS
====================================================================================================

Shape:
(99441, 5)

Columns:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Data Types:
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

First 3 Rows:

                        customer_id                customer_unique_id  customer_zip_code_prefix          customer_city customer_state
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0                     14409                 franca             SP
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3                      9790  sao bernardo do campo             SP
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e                      1151              sao paulo             SP

====================================================================================================
DATASET: GEOLOCATION
====================================================================================================

Shape:
(1000163, 5)

Columns:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

Data Types:
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

First 3 Rows:

   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng geolocation_city geolocation_state
0                         1037       -23.545621       -46.639292        sao paulo                SP
1                         1046       -23.546081       -46.644820        sao paulo                SP
2                         1046       -23.546129       -46.642951        sao paulo                SP

====================================================================================================
DATASET: ORDER_ITEMS
====================================================================================================

Shape:
(112650, 7)

Columns:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

Data Types:
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

First 3 Rows:

                           order_id  order_item_id                        product_id                         seller_id  shipping_limit_date  price  freight_value
0  00010242fe8c5a6d1ba2dd792cb16214              1  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202  2017-09-19 09:45:35   58.9          13.29
1  00018f77f2f0320c557190d7a144bdd3              1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36  2017-05-03 11:05:13  239.9          19.93
2  000229ec398224ef6ca0657da4fc703e              1  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d  2018-01-18 14:48:30  199.0          17.87

====================================================================================================
DATASET: PAYMENTS
====================================================================================================

Shape:
(103886, 5)

Columns:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Data Types:
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

First 3 Rows:

                           order_id  payment_sequential payment_type  payment_installments  payment_value
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card                     8          99.33
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card                     1          24.39
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card                     1          65.71

====================================================================================================
DATASET: REVIEWS
====================================================================================================

Shape:
(99224, 7)

Columns:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Data Types:
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

First 3 Rows:

                          review_id                          order_id  review_score review_comment_title review_comment_message review_creation_date review_answer_timestamp
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb             4                  NaN                    NaN  2018-01-18 00:00:00     2018-01-18 21:46:59
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33             5                  NaN                    NaN  2018-03-10 00:00:00     2018-03-11 03:05:13
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b             5                  NaN                    NaN  2018-02-17 00:00:00     2018-02-18 14:36:24

====================================================================================================
DATASET: ORDERS
====================================================================================================

Shape:
(99441, 8)

Columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Data Types:
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

First 3 Rows:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00

====================================================================================================
DATASET: PRODUCTS
====================================================================================================

Shape:
(32951, 9)

Columns:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Data Types:
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

First 3 Rows:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0

====================================================================================================
DATASET: SELLERS
====================================================================================================

Shape:
(3095, 4)

Columns:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Data Types:
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

First 3 Rows:

                          seller_id  seller_zip_code_prefix     seller_city seller_state
0  3442f8959a84dea7ee197c632cb2df15                   13023        campinas           SP
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844      mogi guacu           SP
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031  rio de janeiro           RJ

====================================================================================================
DATASET: CATEGORY_TRANSLATION
====================================================================================================

Shape:
(71, 2)

Columns:
['product_category_name', 'product_category_name_english']

Data Types:
product_category_name            object
product_category_name_english    object
dtype: object

First 3 Rows:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto

In [9]:
null_summary = []

for name, df in datasets.items():
    for column in df.columns:
        null_count = df[column].isnull().sum()

        null_summary.append({
            "dataset": name,
            "column": column,
            "null_count": null_count,
            "null_percentage": round(
                (null_count / len(df)) * 100, 2
            )
        })

null_report = pd.DataFrame(null_summary)

null_report = null_report[
    null_report["null_count"] > 0
].sort_values(
    ["dataset", "null_percentage"],
    ascending=[True, False]
)

null_report

     dataset                         column  null_count  null_percentage
35    orders  order_delivered_customer_date        2965             2.98
34    orders   order_delivered_carrier_date        1783             1.79
33    orders              order_approved_at         160             0.16
38  products          product_category_name         610             1.85
39  products            product_name_lenght         610             1.85
40  products     product_description_lenght         610             1.85
41  products             product_photos_qty         610             1.85
42  products               product_weight_g           2             0.01
43  products              product_length_cm           2             0.01
44  products              product_height_cm           2             0.01
45  products               product_width_cm           2             0.01
25   reviews           review_comment_title       87656            88.34
26   reviews         review_comment_message       58247            58.70

In [10]:
null_report.to_csv(
    "../docs/null_value_report.csv",
    index=False
)

In [11]:
duplicate_summary = []

for name, df in datasets.items():
    duplicate_count = df.duplicated().sum()

    duplicate_summary.append({
        "dataset": name,
        "total_rows": len(df),
        "duplicate_rows": duplicate_count,
        "duplicate_percentage": round(
            duplicate_count / len(df) * 100, 2
        )
    })

duplicate_report = pd.DataFrame(duplicate_summary)

duplicate_report

                dataset  total_rows  duplicate_rows  duplicate_percentage
0             customers       99441               0                  0.00
1           geolocation     1000163          261831                 26.18
2           order_items      112650               0                  0.00
3              payments      103886               0                  0.00
4               reviews       99224               0                  0.00
5                orders       99441               0                  0.00
6              products       32951               0                  0.00
7               sellers        3095               0                  0.00
8  category_translation          71               0                  0.00

In [12]:
duplicate_report.to_csv(
    "../docs/duplicate_report.csv",
    index=False
)

In [13]:
invalid_orders_customers = orders[
    ~orders["customer_id"].isin(customers["customer_id"])
]

print("Orders with invalid customer_id:")
print(len(invalid_orders_customers))

Orders with invalid customer_id:
0

In [14]:
invalid_order_items = order_items[
    ~order_items["order_id"].isin(orders["order_id"])
]

print("Order items with invalid order_id:")
print(len(invalid_order_items))

Order items with invalid order_id:
0

In [15]:
invalid_products = order_items[
    ~order_items["product_id"].isin(products["product_id"])
]

print("Order items with invalid product_id:")
print(len(invalid_products))

Order items with invalid product_id:
0

In [16]:
invalid_sellers = order_items[
    ~order_items["seller_id"].isin(sellers["seller_id"])
]

print("Order items with invalid seller_id:")
print(len(invalid_sellers))

Order items with invalid seller_id:
0

In [17]:
invalid_payments = payments[
    ~payments["order_id"].isin(orders["order_id"])
]

print("Payments with invalid order_id:")
print(len(invalid_payments))

Payments with invalid order_id:
0

In [18]:
profiling_results = []

for name, df in datasets.items():
    profiling_results.append({
        "dataset": name,
        "rows": len(df),
        "columns": len(df.columns),
        "duplicate_rows": df.duplicated().sum(),
        "total_null_values": int(df.isnull().sum().sum())
    })

profiling_report = pd.DataFrame(profiling_results)

profiling_report

                dataset     rows  columns  duplicate_rows  total_null_values
0             customers    99441        5               0                  0
1           geolocation  1000163        5          261831                  0
2           order_items   112650        7               0                  0
3              payments   103886        5               0                  0
4               reviews    99224        7               0             145903
5                orders    99441        8               0               4908
6              products    32951        9               0               2448
7               sellers     3095        4               0                  0
8  category_translation       71        2               0                  0

In [19]:
profiling_report.to_csv(
    "../docs/data_profiling_report.csv",
    index=False
)

Data Quality Validation

In [20]:
profiling_report

                dataset     rows  columns  duplicate_rows  total_null_values
0             customers    99441        5               0                  0
1           geolocation  1000163        5          261831                  0
2           order_items   112650        7               0                  0
3              payments   103886        5               0                  0
4               reviews    99224        7               0             145903
5                orders    99441        8               0               4908
6              products    32951        9               0               2448
7               sellers     3095        4               0                  0
8  category_translation       71        2               0                  0

In [21]:
null_summary = []

for name, df in datasets.items():
    for column in df.columns:
        null_count = df[column].isnull().sum()

        null_summary.append({
            "dataset": name,
            "column": column,
            "null_count": null_count,
            "null_percentage": round(
                (null_count / len(df)) * 100, 2
            )
        })

null_report = pd.DataFrame(null_summary)

null_report = null_report[
    null_report["null_count"] > 0
].sort_values(
    ["dataset", "null_percentage"],
    ascending=[True, False]
)

null_report

     dataset                         column  null_count  null_percentage
35    orders  order_delivered_customer_date        2965             2.98
34    orders   order_delivered_carrier_date        1783             1.79
33    orders              order_approved_at         160             0.16
38  products          product_category_name         610             1.85
39  products            product_name_lenght         610             1.85
40  products     product_description_lenght         610             1.85
41  products             product_photos_qty         610             1.85
42  products               product_weight_g           2             0.01
43  products              product_length_cm           2             0.01
44  products              product_height_cm           2             0.01
45  products               product_width_cm           2             0.01
25   reviews           review_comment_title       87656            88.34
26   reviews         review_comment_message       58247            58.70

In [22]:
null_report.to_csv(
    "../docs/null_value_report.csv",
    index=False
)

In [23]:
duplicate_summary = []

for name, df in datasets.items():
    duplicate_count = df.duplicated().sum()

    duplicate_summary.append({
        "dataset": name,
        "total_rows": len(df),
        "duplicate_rows": duplicate_count,
        "duplicate_percentage": round(
            (duplicate_count / len(df)) * 100, 2
        )
    })

duplicate_report = pd.DataFrame(duplicate_summary)

duplicate_report

                dataset  total_rows  duplicate_rows  duplicate_percentage
0             customers       99441               0                  0.00
1           geolocation     1000163          261831                 26.18
2           order_items      112650               0                  0.00
3              payments      103886               0                  0.00
4               reviews       99224               0                  0.00
5                orders       99441               0                  0.00
6              products       32951               0                  0.00
7               sellers        3095               0                  0.00
8  category_translation          71               0                  0.00

In [24]:
duplicate_report.to_csv(
    "../docs/duplicate_report.csv",
    index=False
)

In [25]:
checks = {
    "orders_to_customers": len(
        orders[~orders["customer_id"].isin(customers["customer_id"])]
    ),
    
    "order_items_to_orders": len(
        order_items[~order_items["order_id"].isin(orders["order_id"])]
    ),
    
    "order_items_to_products": len(
        order_items[~order_items["product_id"].isin(products["product_id"])]
    ),
    
    "order_items_to_sellers": len(
        order_items[~order_items["seller_id"].isin(sellers["seller_id"])]
    ),
    
    "payments_to_orders": len(
        payments[~payments["order_id"].isin(orders["order_id"])]
    ),
    
    "reviews_to_orders": len(
        reviews[~reviews["order_id"].isin(orders["order_id"])]
    )
}

integrity_report = pd.DataFrame(
    list(checks.items()),
    columns=["relationship", "invalid_records"]
)

integrity_report

              relationship  invalid_records
0      orders_to_customers                0
1    order_items_to_orders                0
2  order_items_to_products                0
3   order_items_to_sellers                0
4       payments_to_orders                0
5        reviews_to_orders                0

In [26]:
integrity_report.to_csv(
    "../docs/referential_integrity_report.csv",
    index=False
)